version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cont-bitacora
    restart: always
    volumes:
      - ./app/:/usr/share/nginx/html/
    ports:
      - "8080:80"
